apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: app-pod

spec:
  template:
     metadata:
       name: app-pod
       labels:
        app: app-pod
     spec:
       containers:
         - name: app-pod
           env:
             - name: DB_SERVER
               value: db-service
             - name: DB_PORT
               value: 31306
             - name: DB_NAME
               value: crudwebdb
             - name: DB_USERNAME
               value: pawank
             - name: DB_PASSWORD
               value: '@pawan'
               #valueFrom:
               #  secretKeyRef:
               #    name: mysql-pass
               #    key: password
           image: pawanitzone/myapp:{{BUILD_NUMBER}}
           #image: pawanitzone/myapp
            ports:
             - containerPort: 80

  replicas: 1
  selector:
    matchLabels:
      app: app-pod
