apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
   name: db-pvc-claim
spec:
  storageClassName: ""
  resources:
   requests:
     storage: 2Gi
  volumeName: db-pv
  accessModes:
    - ReadWriteOnce
