apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: k8s-volume
    fsType: ext4
  #awsElastickBlockStore:
  #  volumeID:
  #  fsType: ext4
