##manual PV provisioning
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-vol
spec:
  storageClassName: ""
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  gcePersistentDisk:
    pdName: db-vol
    fsType: ext4
  #awsElastickBlockStore:
  #  volumeID:
  #  fsType: ext4
