apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db-pod

spec:
  template:
     metadata:
       name: db-pod
       labels:
         app: db-pod
     spec:
       containers:
         - name: db-pod
           #image: pawanitzone/mydb:{{BUILD_NUMBER}}
           image: pawanitzone/mydb:6
           env:
             - name: MYSQL_ROOT_PASSWORD
               value: '@pawan'

           volumeMounts:
           - mountPath: "/usr/lib/mysql"
             name: db-vol
           ports:
             - containerPort: 3306
       volumes:
        - name: db-vol
          persistentVolumeClaim:
            claimName: db-vol-claim
  replicas: 1
  selector:
    matchLabels:
      app: db-pod
