pipeline {
  agent any
    environment {
        PROJECT_ID = 'essential-smoke-274903'
        LOCATION = 'us-central1-c'
        CREDENTIALS_ID = 'gkeweb'
        CLUSTER_NAME = 'hirelab'
                  
    }
  stages {
    stage('Docker Build') {
      steps {
        sh "docker build -t pawanitzone/mydb:${env.BUILD_NUMBER} mysql/."
      }
    }
    stage('Docker Push') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'dockerHubUser', passwordVariable: 'dockerHubPassword', usernameVariable: 'dockerHubUser')]) {
          sh "docker login -u ${env.dockerHubUser} -p ${env.dockerHubPassword}"
          sh "docker push pawanitzone/mydb:${env.BUILD_NUMBER}"
        }
      }
    }
    stage('Docker Remove Image') {
      steps {
        sh "docker rmi pawanitzone/mydb:${env.BUILD_NUMBER}"
      }
    }
    stage('Deploy to GKE') {
       steps{  
	  sh 'kubectl apply -n web -f mysql/secret.yml'
	  //sh 'kubectl apply -n web -f mysql/db-pvc.yml'
	  sh 'cat mysql/db.yml | sed "s/{{BUILD_NUMBER}}/$BUILD_NUMBER/g" |kubectl apply -n web -f -'
          step([$class: 'KubernetesEngineBuilder', projectId: env.PROJECT_ID, clusterName: env.CLUSTER_NAME, location: env.LOCATION, manifestPattern: 'mysql/db.yml', credentialsId: env.CREDENTIALS_ID, verifyDeployments: true])
	  //sh 'kubectl apply -n web -f mysql/db-service.yml'
       }
      }
  }
}



